{{- if .Values.postgres.enabled -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "ideabrd.dbClusterName" . }}
  labels:
    {{- include "ideabrd.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.postgres.instances }}
  {{- with .Values.postgres.imageName }}
  imageName: {{ . }}
  {{- end }}
  storage:
    size: {{ .Values.postgres.storageSize }}
    {{- with .Values.postgres.storageClass }}
    storageClass: {{ . }}
    {{- end }}
  bootstrap:
    initdb:
      database: {{ .Values.postgres.database }}
      owner: {{ .Values.postgres.owner }}
{{- end -}}
